version: '2.4'
services:
  envoy:
    build: 
      context: envoy
    ports:
    - 8080:8080
    - 9901:9901
    depends_on: 
    - blog
  blog:
    build: .
  blog-client:
    build: blog-client
    ports:
      - 8081:80
    depends_on: 
    - blog
