version: '3.7'
services:
  envoy:
    build: 
      context: envoy
    ports:
    - 8080:8080
    - 9901:9901
    depends_on: 
    - blog
  blog:
    build: .
  blog-client:
    build: blog-client
    ports:
      - 8081:80
    depends_on: 
    - blog
  mongodb_container:
    image: mongo:latest
    container_name: 'mongodb_container'
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: